apiVersion: v1
kind: Service
metadata:
  name: samp-api-nodeport
  namespace: default
spec:
  type: NodePort
  selector:
    app: samp-api
  ports:
    - name: web
      port: 3000
      targetPort: web
      nodePort: 30001